import type { Marketplace, User } from '@/types'

export const mockUser: User = {
  id: 'demo-user',
  email: 'demo@example.com',
  name: 'Alex Johnson',
  bio: 'Marketplace enthusiast and digital entrepreneur.',
  avatar: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  _count: { memberships: 0 },
}

export const mockMarketplaces: Marketplace[] = [
  {
    id: 'shopify-partners',
    name: 'Shopify Partners',
    description: 'Join the Shopify ecosystem and build apps, themes, or provide services to merchants worldwide.',
    category: 'E-commerce',
    logo: null,
    website: 'https://partners.shopify.com',
    memberCount: 12400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'upwork',
    name: 'Upwork',
    description: "The world's leading freelancing platform connecting businesses with independent talent globally.",
    category: 'Freelance',
    logo: null,
    website: 'https://upwork.com',
    memberCount: 18200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'etsy-sellers',
    name: 'Etsy Sellers',
    description: 'A global marketplace for unique and creative goods. Perfect for handmade, vintage, and craft items.',
    category: 'E-commerce',
    logo: null,
    website: 'https://etsy.com',
    memberCount: 9800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fiverr-pro',
    name: 'Fiverr Pro',
    description: 'Premium freelance marketplace where top talent delivers exceptional digital services on demand.',
    category: 'Services',
    logo: null,
    website: 'https://fiverr.com',
    memberCount: 14600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    description: 'Sell your creations directly to your audience — software, ebooks, music, design assets, and more.',
    category: 'Digital Products',
    logo: null,
    website: 'https://gumroad.com',
    memberCount: 7300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dribbble',
    name: 'Dribbble',
    description: "The world's leading community for creatives to share, grow, and get hired.",
    category: 'Design',
    logo: null,
    website: 'https://dribbble.com',
    memberCount: 21000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'producthunt',
    name: 'Product Hunt',
    description: 'Discover the best new products in tech. A community for makers and early adopters.',
    category: 'Startup',
    logo: null,
    website: 'https://producthunt.com',
    memberCount: 8900,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'amazon-sellers',
    name: 'Amazon Sellers',
    description: "Sell your products to hundreds of millions of customers on the world's largest online marketplace.",
    category: 'E-commerce',
    logo: null,
    website: 'https://sellercentral.amazon.com',
    memberCount: 32000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'toptal',
    name: 'Toptal',
    description: 'Exclusive network of the top 3% of freelance software developers, designers, and finance experts.',
    category: 'Freelance',
    logo: null,
    website: 'https://toptal.com',
    memberCount: 5600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'redbubble',
    name: 'Redbubble',
    description: 'Sell your original art printed on high-quality products: stickers, apparel, phone cases, and more.',
    category: 'Design',
    logo: null,
    website: 'https://redbubble.com',
    memberCount: 11200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
